language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile
matrix:
  exclude:
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4.2.gemfile
services:
  - redis-server
env:
  - LIT_STORAGE=hash
  - LIT_STORAGE=redis
before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - psql -c 'create database lit_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script: "bundle exec rake test"
