language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.1.gemfile
services:
  - redis-server
env:
  - LIT_STORAGE=hash
  - LIT_STORAGE=redis
before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - psql -c 'create database lit_test;' -U postgres
  - cd test/dummy && RAILS_ENV=test bundle exec rake lit:install:migrations && cd ../..
  - cd test/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd ../..
script: "bundle exec rake test"
