language: ruby
sudo: false
rvm:
  - 2.4.1
gemfile:
  - gemfiles/rails_5.gemfile
env:
  - LIT_STORAGE=hash
before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - psql -c 'create database lit_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script: "bundle exec rake test"
