language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
gemfile:
  - gemfiles/rails-3.gemfile
  - gemfiles/rails-4.gemfile
  - gemfiles/rails-4.1.gemfile
services:
  - redis-server
env:
  - LIT_STORAGE=hash
  - LIT_STORAGE=redis
